# Generated by Django 4.2.29 on 2026-03-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '服务日志',
                'verbose_name_plural': '服务日志',
                'db_table': 'service_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
