# Generated by Django 4.2.29 on 2026-03-30 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompressionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='任务名称')),
                ('original_image', models.FileField(upload_to='images/original/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif', 'webp', 'tiff'])], verbose_name='原始图片')),
                ('compressed_image', models.FileField(blank=True, null=True, upload_to='images/compressed/%Y/%m/%d/', verbose_name='压缩后图片')),
                ('quality', models.CharField(choices=[('low', '低质量 (60%)'), ('medium', '中等质量 (80%)'), ('high', '高质量 (90%)'), ('custom', '自定义')], default='medium', max_length=20, verbose_name='压缩质量')),
                ('target_quality', models.IntegerField(blank=True, help_text='1-100，数值越大质量越好', null=True, verbose_name='目标质量')),
                ('target_format', models.CharField(choices=[('same', '保持原格式'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], default='same', max_length=10, verbose_name='目标格式')),
                ('max_width', models.IntegerField(blank=True, help_text='像素，超过此宽度将等比缩放', null=True, verbose_name='最大宽度')),
                ('max_height', models.IntegerField(blank=True, help_text='像素，超过此高度将等比缩放', null=True, verbose_name='最大高度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, help_text='0-100', verbose_name='进度')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('original_size', models.BigIntegerField(blank=True, null=True, verbose_name='原始文件大小(字节)')),
                ('compressed_size', models.BigIntegerField(blank=True, null=True, verbose_name='压缩后文件大小(字节)')),
                ('compression_ratio', models.FloatField(blank=True, help_text='压缩后大小/原始大小', null=True, verbose_name='压缩比')),
                ('original_width', models.IntegerField(blank=True, null=True, verbose_name='原始宽度')),
                ('original_height', models.IntegerField(blank=True, null=True, verbose_name='原始高度')),
                ('original_format', models.CharField(blank=True, max_length=10, null=True, verbose_name='原始格式')),
                ('compressed_width', models.IntegerField(blank=True, null=True, verbose_name='压缩后宽度')),
                ('compressed_height', models.IntegerField(blank=True, null=True, verbose_name='压缩后高度')),
                ('compressed_format', models.CharField(blank=True, max_length=10, null=True, verbose_name='压缩后格式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '图片压缩任务',
                'verbose_name_plural': '图片压缩任务',
                'db_table': 'image_compression_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
