# Generated by Django 4.2.29 on 2026-03-17 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCompressionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='任务名称')),
                ('original_video', models.FileField(upload_to='videos/original/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'flv', 'wmv'])], verbose_name='原始视频')),
                ('compressed_video', models.FileField(blank=True, null=True, upload_to='videos/compressed/%Y/%m/%d/', verbose_name='压缩后视频')),
                ('quality', models.CharField(choices=[('low', '低质量 (480p)'), ('medium', '中等质量 (720p)'), ('high', '高质量 (1080p)'), ('custom', '自定义')], default='medium', max_length=20, verbose_name='压缩质量')),
                ('target_resolution', models.CharField(blank=True, help_text='例如: 1280x720', max_length=20, null=True, verbose_name='目标分辨率')),
                ('target_bitrate', models.CharField(blank=True, help_text='例如: 1000k', max_length=20, null=True, verbose_name='目标比特率')),
                ('target_fps', models.IntegerField(blank=True, help_text='例如: 30', null=True, verbose_name='目标帧率')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, help_text='0-100', verbose_name='进度')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('original_size', models.BigIntegerField(blank=True, null=True, verbose_name='原始文件大小(字节)')),
                ('compressed_size', models.BigIntegerField(blank=True, null=True, verbose_name='压缩后文件大小(字节)')),
                ('compression_ratio', models.FloatField(blank=True, help_text='压缩后大小/原始大小', null=True, verbose_name='压缩比')),
                ('original_duration', models.FloatField(blank=True, null=True, verbose_name='原始时长(秒)')),
                ('original_resolution', models.CharField(blank=True, max_length=20, null=True, verbose_name='原始分辨率')),
                ('original_bitrate', models.CharField(blank=True, max_length=20, null=True, verbose_name='原始比特率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '视频压缩任务',
                'verbose_name_plural': '视频压缩任务',
                'db_table': 'video_compression_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
