# Generated by Django 4.2.29 on 2026-03-31 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSSFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('video', '视频'), ('image', '图片'), ('audio', '音频'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_ext', models.CharField(blank=True, max_length=20, verbose_name='文件扩展名')),
                ('oss_key', models.CharField(max_length=500, unique=True, verbose_name='OSS对象Key')),
                ('oss_bucket', models.CharField(max_length=100, verbose_name='OSS Bucket')),
                ('oss_url', models.URLField(blank=True, max_length=1000, verbose_name='OSS访问URL')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('completed', '已完成'), ('failed', '失败'), ('deleted', '已删除')], default='uploading', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'OSS文件',
                'verbose_name_plural': 'OSS文件',
                'db_table': 'oss_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
